compliance_pairs = [
    ("'Are firewall rules mandatory under PCI-DSS?'", "'Yes, organizations must configure and maintain firewall rules to protect cardholder data.'"),
    ("'Does FedRAMP require third-party assessments?'", "'Yes, authorization requires a third-party assessment organization (3PAO) review.'"),
    ("'Does GDPR apply outside the EU?'", "'Yes, it applies to any organization processing EU citizen data, regardless of location.'"),
    ("'Does HIPAA require encryption at rest?'", "'Yes, HIPAA recommends encryption at rest to safeguard electronic protected health information.'"),
    ("'Does SOX apply to cybersecurity?'", "'Yes, in the context of protecting financial data and ensuring integrity of financial reporting systems.'"),
    ("'How is CUI protected in CMMC?'", "'By implementing access controls, encryption, and continuous monitoring measures.'"),
    ("'Is MFA required in CMMC?'", "'Yes, multi-factor authentication is mandatory for privileged and remote access under CMMC.'"),
    ("'Is access control part of NIST?'", "'Yes, access control is a key family of controls in NIST 800-53 and 800-171.'"),
    ("'Is encryption required for SOC 2 compliance?'", "'Encryption is recommended for data in transit and at rest to meet security and privacy criteria.'"),
    ("'Is vulnerability management part of CIS?'", "'Yes, vulnerability management is addressed through regular scanning and remediation practices.'"),
    ("'What access controls are required under HIPAA?'", "'HIPAA requires unique user identification, automatic logoff, and encryption to protect ePHI.'"),
    ("'What access controls are required under hipaa??'", "'HIPAA requires unique user identification, automatic logoff, and encryption to protect ePHI. This is required by HIPAA.'"),
    ("'What are the trust principles in SOC 2?'", "'Security, Availability, Processing Integrity, Confidentiality, and Privacy.'"),
    ("'What does CIS Control 6 require?'", "'Maintenance, monitoring, and analysis of audit logs for suspicious activity.'"),
    ("'What does FedRAMP moderate impact level require?'", "'FedRAMP Moderate includes 325 controls from NIST SP 800-53 to protect sensitive data.'"),
    ("'What does NIST 800-171 focus on?'", "'Protecting Controlled Unclassified Information (CUI) in non-federal systems.'"),
    ("'What does PCI-DSS require for cardholder data?'", "'PCI-DSS requires encryption, masking, and limited access to cardholder data.'"),
    ("'What does SOX require for IT systems?'", "'SOX mandates strong access controls, audit logging, and change management for financial systems.'"),
    ("'What is Annex A in ISO 27001?'", "'Annex A provides a list of controls organizations can implement to manage security risks.'"),
    ("'What is CIS Control 1?'", "'CIS Control 1 focuses on inventory and control of enterprise assets.'"),
    ("'What is CMMC Level 2?'", "'CMMC Level 2 requires compliance with NIST 800-171 to protect Controlled Unclassified Information (CUI).'"),
    ("'What is FedRAMP?'", "'FedRAMP is a federal program that standardizes cloud security assessments for service providers.'"),
    ("'What is NIST 800-53 used for?'", "'It provides a catalog of security and privacy controls for federal information systems.'"),
    ("'What is a risk analysis under HIPAA?'", "'A risk analysis identifies potential vulnerabilities to the confidentiality, integrity, and availability of ePHI.'"),
    ("'What is an ISMS in ISO 27001?'", "'An Information Security Management System (ISMS) is a systematic approach to managing sensitive data securely.'"),
    ("'What is requirement 10 in PCI-DSS?'", "'Requirement 10 mandates tracking and monitoring all access to network resources and cardholder data.'"),
    ("'What is section 404 of SOX?'", "'It requires management and external auditors to report on internal controls over financial reporting.'"),
    ("'What is the purpose of a Data Protection Officer under GDPR?'", "'To oversee data protection strategies and ensure GDPR compliance.'"),
    ("'What is the right to erasure under GDPR?'", "'Individuals have the right to have their personal data deleted upon request.'"),
    ("'Who performs SOC 2 audits?'", "'Independent CPAs or firms certified by the AICPA conduct SOC 2 audits.'"),
    ("How do you secure S3 buckets in AWS?", "Enable S3 bucket encryption, disable public access, and apply IAM policies."),
    ("How does GDPR impact data retention?", "GDPR mandates limiting personal data retention to what is necessary for processing."),
    ("What does CMMC require for access control?", "CMMC requires multi-factor authentication and role-based access control."),
    ("What does HIPAA require for data encryption?", "HIPAA mandates encryption for electronic PHI during transmission and at rest."),
    ("What is the purpose of AWS IAM roles?", "IAM roles grant temporary access to AWS services with specific permissions."),
]